let hotels=[
    {
        name: "Royal Residency",
        address: "1 Taj East Gate Road, Agra, Uttar Pradesh, India",
        rating: 4.5,
        facilities: ["Free Wi-Fi", "Swimming Pool", "Restaurant"],
        description: "A luxurious hotel offering stunning views of the Taj Mahal.",
    },
    {
        name: "Agra Grand Hotel",
        address: "18/159, Billochpura, Taj Ganj, Agra, Uttar Pradesh, India",
        rating: 4,
        facilities: ["Free Parking", "Gym", "Spa"],
        description: "A modern hotel with excellent amenities and proximity to the Taj Mahal.",
    },
    {
        name: "Taj View Inn",
        address: "A/3, Taj Nagri Phase 1, Shilpgram, Agra, Uttar Pradesh, India",
        rating: 4.5,
        facilities: ["Breakfast Included", "Conference Room", "Airport Shuttle"],
        description: "Experience the best view of the Taj Mahal from your room at Taj View Inn.",
    },
    {
        name: "Grand Palace Hotel",
        address: "22 Fatehabad Road, Agra, Uttar Pradesh, India",
        rating: 3.5,
        facilities: ["Free Wi-Fi", "Swimming Pool", "Bar"],
        description: "Luxury accommodation with a touch of historical elegance near the Taj Mahal.",
    },
    {
        name: "Agra Heritage Resort",
        address: "25/30 Taj Link Road, Agra, Uttar Pradesh, India",
        rating: 4.5,
        facilities: ["Free Parking", "Spa", "Garden"],
        description: "Immerse yourself in the charm of Agra at the Agra Heritage Resort.",
    },
    {
        name: "Mughal Serenity Hotel",
        address: "14 Taj Ganj, Agra, Uttar Pradesh, India",
        rating: 4,
        facilities: ["Free Wi-Fi", "Fitness Center", "Rooftop Lounge"],
        description: "Experience serenity in the heart of Agra at the Mughal Serenity Hotel.",
    },
    {
        name: "Regal Plaza",
        address: "35/150 Taj Mahal, Eastern Gate Road, Agra, Uttar Pradesh, India",
        rating: 3.5,
        facilities: ["Restaurant", "Conference Hall", "Swimming Pool"],
        description: "Regal Plaza offers a comfortable stay just minutes away from the Taj Mahal.",
    },
    {
        name: "Agra Bliss Suites",
        address: "7 Fatehabad Road, Agra, Uttar Pradesh, India",
        rating: 4.5,
        facilities: ["Free Breakfast", "Spa", "Gym"],
        description: "Indulge in luxury and comfort at Agra Bliss Suites near the iconic Taj Mahal.",
    },
    {
        name: "Taj Horizon View",
        address: "10/21 Taj Nagri Phase 2, Agra, Uttar Pradesh, India",
        rating: 4,
        facilities: ["Rooftop Restaurant", "Free Wi-Fi", "Concierge Service"],
        description: "Enjoy panoramic views of the Taj Mahal from the Taj Horizon View hotel.",
    },
    {
        name: "Heritage Haveli",
        address: "42/45 Kutchery Road, Agra, Uttar Pradesh, India",
        rating: 4.5,
        facilities: ["Traditional Decor", "Garden", "Cultural Events"],
        description: "Immerse yourself in Agra's rich heritage at the charming Heritage Haveli.",
    },
    {
        name: "Sunrise Retreat",
        address: "8/12 Taj Nagri Phase 1, Agra, Uttar Pradesh, India",
        rating: 4,
        facilities: ["Free Parking", "Outdoor Pool", "Fitness Center"],
        description: "Start your day with a view of the sunrise over the Taj Mahal at Sunrise Retreat.",
    },
    {
        name: "Grand Heritage Palace",
        address: "15/78 Fatehabad Road, Agra, Uttar Pradesh, India",
        rating: 4.5,
        facilities: ["Fine Dining", "Luxury Spa", "Lounge Bar"],
        description: "Experience the grandeur of Agra at the Grand Heritage Palace near Taj Mahal.",
    },
    {
        name: "Agra Regency Hotel",
        address: "22 Shahjahan Road, Agra, Uttar Pradesh, India",
        rating: 3.5,
        facilities: ["Conference Facilities", "Free Wi-Fi", "Family-friendly"],
        description: "A comfortable and family-friendly stay awaits you at Agra Regency Hotel.",
    },
    {
        name: "Golden View Residency",
        address: "5/17 Taj East Gate Road, Agra, Uttar Pradesh, India",
        rating: 4,
        facilities: ["Balcony Views", "Free Breakfast", "Business Center"],
        description: "Enjoy the golden hour views of the Taj Mahal from Golden View Residency.",
    },
    {
        name: "Modern Palace Suites",
        address: "12/9 Fatehabad Road, Agra, Uttar Pradesh, India",
        rating: 4,
        facilities: ["Modern Decor", "Roof Terrace", "Concierge Service"],
        description: "Experience modern luxury at the heart of historical Agra at Modern Palace Suites.",
    },
    {
        name: "Agra Greens Hotel",
        address: "31 Taj Link Road, Agra, Uttar Pradesh, India",
        rating: 4,
        facilities: ["Garden Views", "Free Parking", "Outdoor Dining"],
        description: "Relax in the peaceful ambiance of Agra Greens Hotel surrounded by lush greenery.",
    },
    {
        name: "Elegance Residences",
        address: "14/8 Taj Nagri Phase 2, Agra, Uttar Pradesh, India",
        rating: 4.5,
        facilities: ["Elegant Decor", "Spacious Rooms", "Fitness Center"],
        description: "Experience elegance and comfort at Elegance Residences near the Taj Mahal.",
    },
    {
        name: "Royal Taj Retreat",
        address: "6 Taj East Gate Road, Agra, Uttar Pradesh, India",
        rating: 4.5,
        facilities: ["Royal Decor", "Luxury Spa", "Rooftop Lounge"],
        description: "Indulge in royal luxury at Royal Taj Retreat with a majestic view of the Taj Mahal.",
    },
    {
        name: "Agra Dreams Hotel",
        address: "20/32 Fatehabad Road, Agra, Uttar Pradesh, India",
        rating: 4,
        facilities: ["Dreamy Ambiance", "Free Wi-Fi", "Cultural Events"],
        description: "Make your dreams come true with a stay at Agra Dreams Hotel near the Taj Mahal.",
    },
    {
        name: "Serenity Suites",
        address: "9/15 Taj Link Road, Agra, Uttar Pradesh, India",
        rating: 4.5,
        facilities: ["Serenity Garden", "Fitness Center", "Spa"],
        description: "Find serenity and relaxation at Serenity Suites, a peaceful retreat in Agra.",
    }
]

export default hotels;