let hospitals=[
    {
    name: "City Hospital",
    address: "123 Medical Avenue, Agra, Uttar Pradesh, India",
    rating: 4,
    facilities: ["Emergency Services", "Surgery Rooms", "Maternity Ward"],
    description: "A leading hospital providing comprehensive healthcare services to the community.",
  },
  {
    name: "Agra Medical Center",
    address: "55 Health Street, Agra, Uttar Pradesh, India",
    rating: 4.5,
    facilities: ["Diagnostic Imaging", "Specialized Clinics", "Pharmacy"],
    description: "State-of-the-art medical center with a focus on advanced diagnostics and treatments.",
  },
  {
    name: "Taj Memorial Hospital",
    address: "2 Lifesaver Lane, Agra, Uttar Pradesh, India",
    rating: 4.5,
    facilities: ["Intensive Care Unit", "Cardiology Services", "Pediatric Care"],
    description: "Dedicated to providing compassionate and high-quality healthcare services to patients.",
  },
  {
    name: "Sunrise Medical Center",
    address: "78 Wellness Street, Agra, Uttar Pradesh, India",
    rating: 4.5,
    facilities: ["Wellness Programs", "Rehabilitation Services", "Radiology"],
    description: "Promoting wellness and healing at Sunrise Medical Center in Agra.",
  },
  {
    name: "Greenview Hospital",
    address: "33 Nature Lane, Agra, Uttar Pradesh, India",
    rating: 4.5,
    facilities: ["Green Spaces", "Orthopedic Services", "Critical Care"],
    description: "Providing healthcare in a serene and green environment at Greenview Hospital.",
  },
  {
    name: "Agra Heart Institute",
    address: "11 Cardio Street, Agra, Uttar Pradesh, India",
    rating: 5,
    facilities: ["Cardiac Care", "Cardiovascular Surgery", "Electrophysiology"],
    description: "Specializing in heart care and cardiovascular services at Agra Heart Institute.",
  },
  {
    name: "Heritage Health Center",
    address: "28 Cultural Avenue, Agra, Uttar Pradesh, India",
    rating: 4,
    facilities: ["Cultural Events", "Alternative Medicine", "Dietary Services"],
    description: "Blending healthcare with cultural experiences at Heritage Health Center.",
  },
  {
    name: "Unity Medical Hub",
    address: "45 Unity Road, Agra, Uttar Pradesh, India",
    rating: 4.5,
    facilities: ["Comprehensive Care", "Neurology Services", "Cancer Center"],
    description: "A hub of medical excellence offering comprehensive healthcare services.",
  },
  {
    name: "Royal Infirmary",
    address: "7 Royal Avenue, Agra, Uttar Pradesh, India",
    rating: 3.5,
    facilities: ["Royal Services", "VIP Suites", "Advanced Imaging"],
    description: "Experience royal healthcare services at Royal Infirmary in the heart of Agra.",
  },
  {
    name: "Lotus Wellness Hospital",
    address: "19 Spiritual Street, Agra, Uttar Pradesh, India",
    rating: 3.5,
    facilities: ["Holistic Healing", "Yoga Center", "Nutrition Counseling"],
    description: "Focusing on holistic wellness and spiritual healing at Lotus Wellness Hospital.",
  },
  {
    name: "Agra Community Clinic",
    address: "99 Community Avenue, Agra, Uttar Pradesh, India",
    rating: 3,
    facilities: ["Primary Care", "Vaccination Services", "Family Medicine"],
    description: "A community-focused clinic providing essential healthcare services to residents.",
  },
  {
    name: "Riverfront Medical Center",
    address: "24 Riverside Road, Agra, Uttar Pradesh, India",
    rating: 4,
    facilities: ["Scenic Views", "Rehabilitation Services", "Outpatient Care"],
    description: "Situated by the river, offering serene views and comprehensive medical care.",
  },
  {
    name: "Central Children's Hospital",
    address: "15 Kidsway, Agra, Uttar Pradesh, India",
    rating: 4.5,
    facilities: ["Pediatric Specialists", "Child-friendly Environment", "Play Therapy"],
    description: "Dedicated to the health and well-being of children, providing specialized pediatric care.",
  },
  {
    name: "Greenheart Wellness Center",
    address: "37 Eco Lane, Agra, Uttar Pradesh, India",
    rating: 4.5,
    facilities: ["Holistic Wellness", "Nature Therapies", "Mental Health Services"],
    description: "Promoting wellness through eco-friendly practices and holistic health services.",
  },
  {
    name: "Golden Age Nursing Home",
    address: "5 Eldercare Street, Agra, Uttar Pradesh, India",
    rating: 4.5,
    facilities: ["Geriatric Care", "Assisted Living", "Memory Care"],
    description: "Caring for the golden age with specialized services for senior citizens.",
  },
  {
    name: "Agra OrthoCare Institute",
    address: "18 Ortho Avenue, Agra, Uttar Pradesh, India",
    rating: 3.5,
    facilities: ["Orthopedic Surgery", "Sports Medicine", "Joint Replacement"],
    description: "Specializing in orthopedic care and advanced treatments for bone and joint health.",
  },
  {
    name: "Infinite Life Transplant Center",
    address: "63 Organ Boulevard, Agra, Uttar Pradesh, India",
    rating: 4.5,
    facilities: ["Organ Transplants", "Transplant Surgery", "Donor Program"],
    description: "Dedicated to saving lives through organ transplantation and compassionate care.",
  },
  {
    name: "Graceful Maternity Hospital",
    address: "8 Mom-to-Be Street, Agra, Uttar Pradesh, India",
    rating: 4.5,
    facilities: ["Maternity Care", "Labor and Delivery", "Postpartum Support"],
    description: "Providing graceful and compassionate care for expecting mothers and newborns.",
  },
  {
    name: "Agra Mental Wellness Clinic",
    address: "22 Mindful Lane, Agra, Uttar Pradesh, India",
    rating: 4.5,
    facilities: ["Psychiatry Services", "Counseling", "Mental Health Workshops"],
    description: "Supporting mental health and well-being through comprehensive mental wellness services.",
  },
  {
    name: "Rainbow Pediatric Hospital",
    address: "14 Kiddie Lane, Agra, Uttar Pradesh, India",
    rating: 4.5,
    facilities: ["Pediatric Care", "Child Psychology", "Child-friendly Environment"],
    description: "Bringing a spectrum of care to pediatric patients with a focus on child-friendly services.",
  }
];

export default hospitals;